version: "3.7"
services:
  frontend:
    container_name: frontend
    command: bash -c serve -s
    build: frontend
    ports:
      - 5000:5000
    stdin_open: true
    restart: always
    networks:
      - react-express
    depends_on:
      - backend

  backend:
    container_name: backend
    command:
      - npm
      - start
    restart: always
    build: backend
    depends_on:
      - mongo
    networks:
      - express-mongo
      - react-express

  mongo:
    container_name: mongo
    restart: always
    image: mongo:4.2.0
    volumes:
      - ./data:/data/db
    networks:
      - express-mongo
networks:
  react-express:
  express-mongo:
